### ISSUE TITLE
Switching to @apollo/client/core?

### ISSUE THREAD

**Issue by JonasKruckenberg** [fubhy/graphql-transport-electron#15]
So currently I need to install `react` as a peer dependency to use this module even though I'm using vue.
As per the [Apollo docs](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#using-apollo-client-without-react) they recommend import the apollo client from `@apollo/client/core` if you don't need react support.
That'd be awesome!

**Comment by fubhy** [comment]
Yeah we can do that. Would you mind submitting a pull request?

**Comment by JonasKruckenberg** [comment]
Sure, wait a second!

**Comment by fubhy** [comment]
Sweet, thanks!
