### ISSUE TITLE
"An object could not be cloned" electron@8

### ISSUE THREAD

**Issue by layerssss** [fubhy/graphql-transport-electron#7]
I'm setting a new project and ran into this:

```
Uncaught Error: An object could not be cloned.
    at new ApolloError (ApolloError.js?40ae:27)
    at ObservableQuery.getCurrentResult (ObservableQuery.js?010a:101)
    at QueryData._this.getQueryResult (QueryData.js?74a3:28)
    at QueryData.getExecuteResult (QueryData.js?74a3:152)
    at QueryData.execute (QueryData.js?74a3:101)
    at eval (useBaseQuery.js?b9a7:38)
    at useDeepMemo (useDeepMemo.js?31e9:9)
    at useBaseQuery (useBaseQuery.js?b9a7:38)
    at useQuery (useQuery.js?f933:4)
    at useData (useData.js?c525:8)
```

It wasn't hitting the resolver in the main process. I did a quick search and I suspect it was broken by this change in electron@8 (I have electron@9)

https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception

**Comment by layerssss** [comment]
@fubhy It looks like removing the `context` being sent through client had it fixed.

Remove this line: https://github.com/fubhy/graphql-transport-electron/blame/master/src/client.ts#L32

**Comment by jimmed** [comment]
I tried the workaround as proposed by @layerssss, but without passing `context` on each query, I lose the authorisation headers I'm setting from the renderer.

I found that by cloning the object via JSON.parse/serialize, I was able to make the `context` safe to pass over IPC.

I'll raise a pull request for this shortly!

**Comment by layerssss** [comment]
@jimmed I thought the apollo`context` on client-side and server-side are seperate, just like how you normally could use it in `apollo-express` and on Web. Wouldn't it be a little bit diverging from that to pass the client side context directly onto server?

ps. here is an example apollo-http-batch-link's request

![image](https://user-images.githubusercontent.com/1559832/87217657-c45f0780-c39f-11ea-8b0f-2c00264b9659.png)

**Comment by jimmed** [comment]
The client context is an object that's used by the HttpLink to make the request -- the typical use case is passing an auth token via a header.

If it's not passed in, there's no way of providing context to the underlying HttpLink without sending it via a separate IPC channel. I hope this makes sense!

![fig 1](https://user-images.githubusercontent.com/318961/87228706-e30ecf80-c39a-11ea-8a82-4e846d538f5e.png)

In this diagram, the query with auth header is passing its auth header via the context object. If the IPC link doesn't transmit this, then it won't be available for the HttpLink to set the auth header on the request it makes.
